### ISSUE TITLE
AEDAT decoder

### ISSUE THREAD

**Issue by aMarcireau** [neuromorphic-paris/loris#5]
Hey @biphasic 

I wrote a fast AEDAT decoder with a Python wrapper. I thought it could be nice to make Loris depend on it, to provide seamless decoding of AEDAT as well. The package is available on PyPI (https://pypi.org/project/aedat/).

There are a few caveats, though:
- it is only compatible with AEDAT 4
- it can only read files, not write them

I was not able to directly add support to Loris, as the library is written in Rust, not C++ (I started it as an exercise to learn Rust). Feel free to close this issue if you'd rather keep Loris dependency free.

Cheers,
Alex

**Comment by biphasic** [comment]
Amazing! That's a great idea. How can I help?

**Comment by aMarcireau** [comment]
If you like the idea, I can make a PR to Loris (Python only) which will:
- add a dependency to the aedat package
- use it to decode files with the `.adept` extension
- return a special error message mentioning that only aedat4 is supported if decoding fails with a `.aedat` file

I will need your help to upload the new version to PyPI.

**Comment by biphasic** [comment]
excellent. Could you please provide a small sample file encoded with aedat4, so I can include some tests! Once everything passes, I will merge and upload a new major version to pypi
